/** Declaration file generated by dts-gen */

export class Morris {
    constructor(rules: any);

    addRule(rule: any): any;

    apply(text: any, context: any, rule: any): any;

    asyncFormat(text: any, context: any, callback: any): any;

    buildRuleMap(): any;

    format(text: any, context: any, callback: any): any;

    getRuleID(): any;

}

